#!/usr/bin/env python
PACKAGE = "reader"

from dynamic_reconfigure.parameter_generator_catkin import *

gen = ParameterGenerator()
gen.add("isDDK", bool_t, 0, "used to decide the computing algorithm", True)
exit(gen.generate("reader", "reader", "algorithm_param"))
